version:  "3.8"

services:
  accounts:
    image: ramspringms/accounts:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - easybank-network
      
  loans:
    image: ramspringms/loans:latest
    mem_limit: 700m
    ports:
      - "9090:9090"
    networks:
      - easybank-network
                
  cards:
    image: ramspringms/cards:latest
    mem_limit: 700m
    ports:
      - "9091:9091"
    networks:
      - easybank-network
      
  configserver:
    image: ramspringms/configserver:latest
    mem_limit: 700m
    ports:
      - "8071:8071"
    networks:
      - easybank-network    

networks:
  easybank-network: {}   
      
    