version:  "3.8"

services:


  grafana:
    image: "grafana/grafana:latest"
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
    networks:
      - easybank-network
    depends_on:
      - prometheus
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
    networks:
      - easybank-network
 
  zipkin:
    image: openzipkin/zipkin
    mem_limit: 700m
    ports:
      - "9411:9411"
    network:
      - easybank-network    

  configserver:
    image: ramspringms/configserver:latest
    mem_limit: 700m
    ports:
      - "8071:8071"
    networks:
      - easybank-network
    depends_on:
      - zipkin
    environment:
      SPRING_PROFILE_ACTIVE: default
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/
      
  eurekaserver:
    image: ramspringms/eurekaserver:latest
    mem_limit: 700m
    ports:
      - "8070:8070"
    networks:
      - easybank-network
    depends_on:
      - configserver
      
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILE_ACTIVE: default 
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/

     
      
      
      
  accounts:
    image: ramspringms/accounts:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - easybank-network
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILE_ACTIVE: default 
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/

      
  loans:
    image: ramspringms/loans:latest
    mem_limit: 700m
    ports:
      - "9090:9090"
    networks:
      - easybank-network
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILE_ACTIVE: production 
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/

                
  cards:
    image: ramspringms/cards:latest
    mem_limit: 700m
    ports:
      - "9091:9091"
    networks:
      - easybank-network
    depends_on: 
      - configserver
      - eurekaserver
    deploy:
      restart_policy: 
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILE_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/  
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/

      
  gatewayserver:
    image:ramspringms/gatewayserver:latest
    mem_limit:700m
    ports:
      - "8072:8072"
    networks:
      - easybank-network
    depends_on:
      - configserver
      - eurekaserver
      - cards
      - loans
      - accounts
    deploy:
      restart_policy:
        condition: on-failure
        delay: 45s
        max_attempts: 3
        window: 180s
    environment:
      SPRING_PROFILE_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/

    

networks:
  easybank-network: {}   
      
    